baseURL: "https://SolaKitsune.github.io/"
title: "我的小说网站"
theme: "hugo-book"
languageCode: "zh-CN"
defaultContentLanguage: "zh"

# 强制输出 UTF-8
outputs:
  home: ["HTML"]
  page: ["HTML"]
  section: ["HTML"]

params:
  BookTheme: "auto"
  BookToC: true
  BookSection: "docs"  
  BookSearch: true   
  BookDateFormat: "2006-01-02" 